name: Deploy Blog
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build blog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
            node-version: '22'
            cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Check and build the blog
        run: npm run build
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: blog-build
          path: dist/
  deploy:
    name: Deploy blog
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: blog-build
          path: ./dist
      - name: Install SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'some-random-value'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avz ./dist ${{ secrets.SSH_USER }}@{{ secrets.SSH_HOST }}:/var/www/blog